---
version: "3.9"
services:
  main:
    build:
      context: .
      args:
        aqua_version: v0.1.0-9
        aqua_installer_version: v0.1.0-0
    tty: true
    stdin_open: true
    volumes:
    - ".:/workspace"
    working_dir: /workspace
    environment:
    - "PATH=/workspace/.aqua/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    - GITHUB_TOKEN
