---
name: integration-test
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AQUA_LOG_LEVEL: debug
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.17.7'

    - run: go build -o /usr/local/bin/aqua ./cmd/aqua
    - run: echo "${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua/bin" >> "$GITHUB_PATH"
    - run: echo "AQUA_GLOBAL_CONFIG=$PWD/tests/aqua-global.yaml:$PWD/tests/aqua-global-2.yaml" >> "$GITHUB_ENV"
    - run: echo "standard,kubernetes-sigs/kind" | aqua g -f -
    - run: echo "x-motemen/ghq" | aqua g -f -
    - run: echo "local,aquaproj/aqua-installer" | aqua -c tests/aqua-global.yaml g -f -
    - run: aqua g x-motemen/ghq aquaproj/aqua-installer
    - run: echo cli/cli | aqua g -f - x-motemen/ghq aquaproj/aqua-installer

    - run: aqua list
    - run: aqua i -l -a
      working-directory: tests
    - run: cmdx -v
      working-directory: tests
    - run: aqua i --test
      working-directory: tests
    - run: aqua which golangci-lint
      working-directory: tests
    - run: aqua which go
    - run: golangci-lint version
    - run: kind version
      working-directory: tests
    - run: kind version
    - run: restic version
    - run: migrate -version
    - run: ghq -version
    - run: gh version
    - run: tfenv --version
    - run: aqua -c tests/aqua-global.yaml g local,kubernetes-sigs/kustomize
    - run: btop -v

    - run: aqua g -i suzuki-shunsuke/tfcmt
      working-directory: tests
    - run: git diff aqua.yaml
      working-directory: tests

    - run: aqua-installer -v v0.8.1 -i /tmp/aqua
