---
name: integration-test
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - run: go build -o /usr/local/bin/aqua ./cmd/aqua
    - run: echo "$HOME/.aqua/bin" >> $GITHUB_PATH
    - run: echo "AQUA_GLOBAL_CONFIG=$PWD/aqua-global.yaml:$PWD/aqua-global-2.yaml" >> $GITHUB_ENV

    - run: aqua list
    - run: aqua i -l -a
    - run: cmdx -v
    - run: aqua i --test
    - run: golangci-lint version
    - run: kind version
    - run: restic version
    - run: migrate -version
    - run: ghq -version
    - run: gh version
