---
name: integration-test
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AQUA_LOG_LEVEL: debug
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - run: go build -o /usr/local/bin/aqua ./cmd/aqua
    - run: echo "$HOME/.aqua/bin" >> $GITHUB_PATH
    - run: echo "AQUA_GLOBAL_CONFIG=$PWD/aqua-global.yaml:$PWD/aqua-global-2.yaml" >> $GITHUB_ENV
    - run: echo "standard,kubernetes-sigs/kind" | aqua g -f -
    - run: echo "standard,x-motemen/ghq" | aqua g -f -
    - run: echo "inline,aquaproj/aqua-installer" | aqua g -f -

    - run: aqua list
    - run: aqua i -l -a
      working-directory: tests
    - run: cmdx -v
      working-directory: tests
    - run: aqua i --test
      working-directory: tests
    - run: aqua which golangci-lint
      working-directory: tests
    - run: aqua which go
    - run: golangci-lint version
    - run: kind version
      working-directory: tests
    - run: kind version
    - run: restic version
    - run: migrate -version
    - run: ghq -version
    - run: gh version
    - run: tfenv --version
    - run: aqua-installer -v v0.8.1 -i /tmp/aqua
